### ISSUE TITLE
npm install jslib-base Error

### ISSUE THREAD

**Issue by wyqsess** [yanhaijing/jslib-base#17]
### What problem

npm install --save jslib-base时发生报错

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for jslib-base
```

### Environment

npm版本5.6.0

### Other

npm官网上也未搜索到jslib-base
https://www.npmjs.com/search?q=jslib-base

**Comment by yugasun** [comment]
@yanhaijing when I run `npm info jslib-base`, is show that:

```
Unpublished by yanhaijing on 2018-10-09T09:02:19.074Z
```

so this module can not be installed any more, and I find [@jsmini/base](https://github.com/jsmini/base) forked from [jslib-base](https://github.com/yanhaijing/jslib-base), I guess you will migrate it to `@jsmini`, but I can not find `@jsmini/base` on `npmjs.com` too.

So when will you publish, or what is your plan?

**Comment by yanhaijing** [comment]
NPM package not available, please `git clone` to use
