### ISSUE TITLE
切换为TS后, 测试不通过

### ISSUE THREAD

**Issue by CozySnail** [yanhaijing/jslib-base#18]
在安装文档中的方法切换为ts的话测试不能通过

**Comment by yanhaijing** [comment]
>支持JS 和 TS 切换，需要更改下面的地方
> 1. package.json中的srctype和scripts
> 2. test/test.js中require文件的方式
> 3. test/browser/index.html中require文件的方式

2改了吗？需要修改下`test/test.js`中require的测试文件

**Comment by CozySnail** [comment]
都改过了, 已经ok了, 是我环境有问题,谢啦

**Comment by yanhaijing** [comment]
@CozySnail 好的感谢使用，感谢反馈，有兴趣加入 [jsmini](https://github.com/jsmini) 吗
