### ISSUE TITLE
Hello! Is there a bug?

### ISSUE THREAD

**Issue by Zenquan** [yanhaijing/jslib-base#2]
os: windows 10

![default](https://user-images.githubusercontent.com/38183707/45098588-e100d780-b157-11e8-8d7d-d3d615248db8.PNG)

**Comment by Zenquan** [comment]
os: windows 10
git bash
![2](https://user-images.githubusercontent.com/38183707/45106894-7dcc7080-b16a-11e8-9214-bdb4cdc30b8e.PNG)

你好，试了一下mac，确实可以的

**Comment by yanhaijing** [comment]
嗯嗯，还没兼容windows，主要是一些原生命令，求提pr o(╯□╰)o

**Comment by yanhaijing** [comment]
目前已经兼容windows了，感谢反馈

**Comment by yanhaijing** [comment]
@Zenquan 你好考虑加入 jsmini吗？添加微信 yanhaijing123
https://github.com/jsmini
