### ISSUE TITLE
rollup 官方月已经升级到 1.8 了，目前 jslib-base 使用到是 0.57.1 版本

### ISSUE THREAD

**Issue by jianglin-wu** [yanhaijing/jslib-base#21]
### What problem

Description of the problem, as detailed as possible.

### Environment

- Mobile: MI6
- System: Android7.1.1
- Browser：Chrome61
- jslib-base version: 0.2.0
- some other information

### Online demo

Please provide online demo if possible.

### Other

some other information.

**Comment by yanhaijing** [comment]
嗯嗯，要更上步伐了，欢迎提个 pr哈

**Comment by jinwyp** [comment]
请看我这个fork项目, 全部升级到最新版本的库

https://github.com/jinwyp/quickapp-h5

**Comment by yanhaijing** [comment]
@jinwyp haode

**Comment by imvkmark** [comment]
版本已经升级为最新
```
  "devDependencies": {
    "@babel/cli": "^7.1",
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/register": "7.*",
    "@js-lib/cli": "^1.6.0",
    "babel-plugin-istanbul": "6.0",
    "coveralls": "3.1",
    "cross-env": "^7",
    "es5-shim": "^4.5",
    "eslint": "^7",
    "expect.js": "^0.3",
    "mocha": "^8.1",
    "nyc": "^15",
    "rimraf": "^3",
    "rollup": "^2.26",
    "rollup-plugin-babel": "^4.0",
    "rollup-plugin-commonjs": "^10",
    "rollup-plugin-node-resolve": "^5.2",
    "rollup-plugin-uglify": "^6",
    "source-map-support": "^0.5"
  },
```

可以运行

可以参考这个文件: https://github.com/imvkmark/poppy-js-util/blob/master/package.json

**Comment by yanhaijing** [comment]
好的，感谢，我有时间更新下，当初支持旧版本主要是为了支持node0.12 版本的build，现在看起来好像不需要了，需要测试旧版本兼容性的，可以用build完的文件去测试

**Comment by yanhaijing** [comment]
终于有时间升级了，2.0发布了，全部升级为最新版，感谢 @imvkmark @jinwyp 提供的支持
