### ISSUE TITLE
项目里面不能使用对象扩展的语法.

### ISSUE THREAD

**Issue by PinghuaZhuang** [yanhaijing/jslib-base#22]
### What problem

let obj = {}
let target = { ...obj }
编译的时候报错. 
添加 "transform-object-rest-spread" 插件没有作用.

### Environment

- Mobile: MI6
- System: Android7.1.1
- Browser：Chrome61
- jslib-base version: 0.2.0
- some other information

### Online demo

Please provide online demo if possible.

### Other

some other information.

**Comment by yanhaijing** [comment]
src

```js
let obj = {}
let target = { ...obj }
```

output

```js
var obj = {};

var target = _objectSpread({}, obj);
```

我看已经被build了哈？

**Comment by PinghuaZhuang** [comment]
我使用的是比较旧的版本, 更新后没问题.
