### ISSUE TITLE
import() 语法不支持.

### ISSUE THREAD

**Issue by PinghuaZhuang** [yanhaijing/jslib-base#23]
在 config.js 配置中添加 '@babel/plugin-transform-runtime', .babelrc 也添加了. 还有 Symbol 也不能被转化. 在 IE 中不能使用.

**Comment by jinwyp** [comment]
看我的这个fork 吧 

https://github.com/jinwyp/quickapp-h5

支持 import,  全部升级到最新版本的库

几点注意:

1 uglify = require('rollup-plugin-uglify'); 要改成 (prod && uglify.uglify())
2 引入jsdom 支持命令行 用window变量.
3 mocha 命令行 支持 import 语法 .  npm run mocha 
(mocha --require @babel/register ./test/**/*.js)

问题, test/broser/index.html 里面 还是不支持 import 语法.   需要研究.

**Comment by yanhaijing** [comment]
@jinwyp 目前已经升级了cli了，一个命令即可完成新建和更新

**Comment by yanhaijing** [comment]
> https://github.com/jinwyp/quickapp-h5

2.0版本发布了，这个问题已经可以了
