### ISSUE TITLE
代码压缩问题

### ISSUE THREAD

**Issue by BUPTlhuanyu** [yanhaijing/jslib-base#32]
### 问题是什么
npm run build:aio的时候报错

### 环境
- 系统：win 10
- node版本：10.13.0
- npm版本：6.4.1

### 在线例子
无

### 其他
由于uglify-js is able to transpile only es5 syntax. If you want to transpile es6+ syntax use terser instead，所以会报错，是否考虑将脚手架的uglify-js换成 terser ，换成terser之后可以解决

**Comment by BUPTlhuanyu** [comment]
同时还需要将rollup升级到最新版本，terser才能生效

**Comment by yanhaijing** [comment]
2.0发布了，已经替换为terser了
