### ISSUE TITLE
是否有考虑直接用babel打包成lib/ es/等文件夹。

### ISSUE THREAD

**Issue by yanguoyu** [yanhaijing/jslib-base#4]
### 问题是什么
因为有些开源库并不希望打包成整体的min.js。这样方便使用时在进行rollup。
另外有考虑升级babel7吗？

**Comment by yanhaijing** [comment]
我觉得对外可以提供一个文件的，对rollup也没什么问题吧？给rollup的版本没有把npm包打进去，所以也没什么问题吧？
因为有treeshake，所以不会有体积问题

**Comment by yanguoyu** [comment]
我以为rollup 会把你示例中的A和B treeshake掉，结果不会treeshake掉。
另外如果有文件没有被引用到就不会被打包，那么所有的都必须通过index.js导出。比如lodash这种工具库就没有通过index.js进行导出。

**Comment by yanhaijing** [comment]
treeshake是在用户的打包工具里做的，库的打包工具不做treeshake，不能lodash比，那个库太大了，我这个是为小而美的库服务的，写那么大的库估计就不会用我这个工具了，😆
不过倒是可以提供个选项，编译出来一份不合并的文件

**Comment by yanguoyu** [comment]
我试了下如果不使用那个rollup-plugin-babel，对于es和cjs版本rollup在打包时会把A和B treeshake掉，使用这个插件就不行，也没看到rollup-plugin-babel里面有说明这个功能呢。

**Comment by yanhaijing** [comment]
A B被index引用了，但是index.js并没有使用A B，用户在引用最终的打包文件时，只要已压缩就会把 A B压缩掉

如果index.js暴漏出去的方法，没有被用户使用，可以通过用户的shakeing 去掉

**Comment by yanhaijing** [comment]
另外有考虑升级babel7吗
-----------
这个是考虑的，欢迎来提pr啊

**Comment by yanhaijing** [comment]
欢迎来提pr啊

**Comment by yanguoyu** [comment]
好的

**Comment by yanhaijing** [comment]
@yanguoyu 考虑加入jsmini吗？添加微信 yanhaijing123
