### ISSUE TITLE
创建新库无法默认使用 yarn

### ISSUE THREAD

**Issue by wy1009** [yanhaijing/jslib-base#55]
### 问题是什么
执行 `npx @js-lib/cli new mylib` 创建新库，只能选择 `npm` 和 `no install`，无法选择使用 yarn。
<img width="158" alt="image" src="https://github.com/yanhaijing/jslib-base/assets/18343973/67a10502-35bd-44c6-a973-d8a20106420f">
选择 `no install`，会在后续要求安装 `only-allow` 并强制使用 `npm`，需手动变更 `package.json` 里 `preinstall` 的配置解决。
搜了下开发者过往的文章，在设计意图里有看到“使用 npm 还是 yarn 维护项目，或者暂时不自动安装依赖”，所以不知道这是 bug 还是 feature。

### 环境
- 系统：mac 13.5.2
- node版本：18.13.0
- npm版本：8.19.3
- 其他版本信息

### 在线例子
如果有请提供在线例子

### 其他
其他信息

**Comment by Allenmcc** [comment]
你的邮件已收到，谢谢！

**Comment by yanhaijing** [comment]
这是一个 feature，在2.0里去掉了对 yarn 的支持，这主要是因为，并未提供 yarn.lock 文件，这就不能保证 yarn 安装完，一定能够运行。
如果想使用 yarn 的话，可行的步骤如下：
第一步，先用 npm 安装，有了node_modules 后
第二步，在使用 yarn 安装
第三步，测试功能成功后，删掉 package-lock.json，提交 yarn.lock 即可

**Comment by wy1009** [comment]
> 这是一个 feature，在2.0里去掉了对 yarn 的支持，这主要是因为，并未提供 yarn.lock 文件，这就不能保证 yarn 安装完，一定能够运行。
> 
> 如果想使用 yarn 的话，可行的步骤如下： 第一步，先用 npm 安装，有了node_modules 后 第二步，在使用 yarn 安装 第三步，测试功能成功后，删掉 package-lock.json，提交 yarn.lock 即可
> 
> 补充：现在有三个工具 npm yarn pnpm，每个工具不同版本，lock格式还不一样，不想维护这么多个lock文件，通过npm作为一个媒介，可以保证安装正确性，也能让大家使用自己想用的包管理工具



> 这是一个 feature，在2.0里去掉了对 yarn 的支持，这主要是因为，并未提供 yarn.lock 文件，这就不能保证 yarn 安装完，一定能够运行。
> 
> 如果想使用 yarn 的话，可行的步骤如下： 第一步，先用 npm 安装，有了node_modules 后 第二步，在使用 yarn 安装 第三步，测试功能成功后，删掉 package-lock.json，提交 yarn.lock 即可
> 
> 补充：现在有三个工具 npm yarn pnpm，每个工具不同版本，lock格式还不一样，不想维护这么多个lock文件，通过npm作为一个媒介，可以保证安装正确性，也能让大家使用自己想用的包管理工具

收到，感谢解答！

**Comment by yanhaijing** [comment]
我感觉加一个yarn的支持也行，yarn的好弄，pnpm的麻烦 ಥ_ಥ
